server:
  port: 8082
  tomcat:
    max-swallow-size: 2MB
    max-http-form-post-size: 2MB

spring:
  application:
    name: ingestion-service

  profiles:
    include: observability

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080/auth/realms/fnmp}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      client-id: ingestion-service
      retries: 3
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max.request.size: 1048576
        compression.type: snappy

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 4
      timeout: 2000ms

resilience4j:
  retry:
    instances:
      kafkaPublish:
        maxAttempts: 3
        waitDuration: 500ms
        retryExceptions:
          - org.springframework.kafka.KafkaException

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: kafka, circuitbreakers
        liveness:
          include: ping, diskSpace