apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.articleService.name }}
  labels:
    app: {{ .Values.articleService.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.articleService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.articleService.name }}