apiVersion: v1
kind: Secret
metadata:
  name: fnmp-secrets
  labels:
    app: {{ include "fnmp.fullname" . }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | default "" | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | default "" | quote }}